config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [ :new, :create, :destroy ]

  resources :users, only: [ :show, :new, :create ]

  get '/signin' => 'sessions#new'

  delete '/signout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get '/company' => 'static_pages#company'

  get '/projects' => 'static_pages#projects'

  get '/media' => 'static_pages#media'

  get '/contact' => 'static_pages#contact'

  
  root 'static_pages#company'

  get '*path' => redirect( '/' )
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :name, presence: true
  validates :password, confirmation: true, length: { minimum: 6 }
  # validates :password_confirmation, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }

  before_save { |user| user.email.downcase! }
  before_save :create_sess_token

  private

    def create_sess_token
      self.sess_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to( current_user ) if signed_in?
  end

  def create
    user = User.find_by_email( session_params[:email] )

    if user && user.authenticate( session_params[:password] )
      sign_in user
      redirect_to user
    else
      # flash[:error] = "Неправильный логин или пароль"
      @error = "Неправильный логин или пароль"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

    def session_params
      params.require( :session ).permit( :email, :password )
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def company
    @current_nav = :company
  end

  def projects
    @current_nav = :projects
  end

  def media
    @current_nav = :media
  end

  def contact
    @current_nav = :contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: :show

  def show
    unless signed_in? && ( current_user.id == params[:id].to_i )
      redirect_to root_path
    end
  end

  def new
    unless signed_in?
      @user = User.new
    else
      redirect_to current_user
    end
  end

  def create
    @user = User.new( user_params )

    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def set_user
      @user = User.find( params[:id] ) rescue( redirect_to root_path )
    end

    def user_params
      params.require( :user ).permit( :name, :email, :password, :password_confirmation )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_elem name, path, current = false
    if current
      "<li class='current'>#{link_to( name, path )}</li>".html_safe
    else
      "<li>#{link_to( name, path )}</li>".html_safe
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in( user )
    cookies.permanent[:sess_token] = user.sess_token
    self.current_user = user
  end

  def current_user=( user )
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_sess_token( cookies[:sess_token] )
    @current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete( :sess_token )
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.slim
div class="bottom"
  div class="table_bottom"
    table
      tr
        td rowspan="2" = image_tag "email.png"
        td Email
        td rowspan="2" = image_tag "phone.png" 
        td Телефон
        td id="last_td" rowspan="2"
          a<> href="#" = image_tag "facebook.png"
          a<> href="#" = image_tag "vk.png"
          a<> href="#" = image_tag "instagramm.png"
          a<> href="#" = image_tag "pinterest.png"
          a<> href="#" = image_tag "odnoklassniki.png"
      tr
        td info@gyrenation.com
        td +7 (123) 456-78-90

  div class="hr"
    hr
                                                                                                                                                                                                          div class="logo_bottom" style="clear: right"
    = image_tag "logo_bottom.png", alt: "Лого"

app/views/application/_header.html.slim
div class="page"
  div class="lang"
    table
      tr
        td 
          span RU
        td 
          a href="" = image_tag "rus.gif", alt: "Russian"
        td 
          span EN
        td 
          a href="" = image_tag "us.gif", alt: "English"
        td 
          - if signed_in?
            | &nbsp;
            = link_to current_user.name, current_user
            | &nbsp;
            = link_to "Выйти", signout_path, method: :delete
          - else
            | &nbsp;
            = link_to "Войти", signin_path
                                                                                                                         
  div class="logo" style="clear: right"
    = image_tag "logo_big.png", alt: "Лого"

  div class="nav"
    ul
      = nav_elem( "О компании", company_path, @current_nav == :company )
      = nav_elem( "Проекты", projects_path, @current_nav == :projects )
      = nav_elem( "Медиа", media_path, @current_nav == :media )
      = nav_elem( "Контакты", contact_path, @current_nav == :contact )

app/views/application/_image.html.slim
div class="image"
  = image_tag "photo.png", alt: "photo"
    
  div class="social"
    p 
      a href="" = image_tag "facebook.png"
    p 
      a href="" = image_tag "vk1.png"
    p 
      a href="" = image_tag "instagramm1.png"
    p 
      a href="" = image_tag "pinterest1.png"
    p 
      a href="" = image_tag "twitter1.png"
    p 
      a href="" = image_tag "odnoklassniki.png"
    

app/views/layouts/application.html.slim
doctype html
html

  head

    title 
      = yield :title
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    
  body

    = render 'header'

    = yield

    = render 'footer'

app/views/static_pages/company.html.slim
- provide :title, 'О компании &bull; GyreNation'

= render 'image'

div class="page"

  div class="text"
    div class="left"
      p align="justify" В 1992 году была основана компания «S-Mail», которая зарекомендовала себя на рынке, продавая электронную почту с защитой почтовой базы шифрованием
        от третьих лиц под единым названием с компанией
      p align="justify" В 2014 году компания расширила спектр своей деятельности и провела ребрендинг, в том числе сменив название компании на GYRENATION.
    div class="right"
      p align="justify" Основным направлением деятельности компании являются современные информационные технологии.
      p align="justify"
        | Принципы работы: 
        ul
          li Легкость в использовании
          li Максимально автоматизированный функционал
          li Использование в разработке только последние достижения информационных технологий

    div class="table"
      table
        tr
          td class="left-td" = image_tag "easy.png", alt: "Легкость"
          td class="center-td" = image_tag "it.png", alt: "Исследование"
          td class="right-td" = image_tag "automatically.png", alt: "Функционал"
        tr
          td class="left-td" Легкость в использовании
          td class="center-td" Использование в разработке только последних достижений в области IT
          td class="right-td" Максимально автоматизированный функционал

    div class="video"
      iframe src="https://player.vimeo.com/video/132209813" width="100%" height="450" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen

app/views/static_pages/contact.html.slim
- provide :title, 'Контакты'

= render 'image'

div class="page"
  div class="map"
    script type="text/javascript" charset="utf-8" src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=f06olXaki1mRaYXUHPhGr7C_Ll3YwhrU&width=100%&height=450"

  div class="contact"
    h3 Обратная связь
    form
      table class="form-contact"
        tr
          td 
            label Ваше имя
          td 
            label Email
        tr
          td 
            input name="name" placeholder="Ваше имя"
          td 
            input name="email" type="email" placeholder="Ваш email"
        tr
          td colspan="2" Сообщение
        tr
          td colspan="2"
            textarea name="message" placeholder="Введите Ваше сообщение"

      input id="submit" name="submit" type="submit" value="Отправить"

  div style="clear:both;"


 

app/views/static_pages/media.html.slim
- provide :title, 'Медиа'

= render 'image'

div class="page"

  div class="media"
    div class="one-media"
      span class="date" 01.05.2015
      a href="#" onclick="diplay_hide('#media-1');return false;" &nbsp;- Рекламный ролик №1
      div id="media-1" style="display: none;"
        div class="image"
          = image_tag "video1.jpg", alt: "photo"
        p class="opisanie" Описание
        p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, quidem? Ullam ipsa eius ad facere, aut alias. Quidem animi harum, recusandae illo enim cumque, earum, 
          quod modi deserunt amet fugit!

  div class="media"
    div class="one-media"
      span class="date" 02.06.2015
      a href="#" onclick="diplay_hide('#media-2');return false;" &nbsp;- Рекламный ролик №2
      div id="media-2" style="display: none;"
        div class="image"
          = image_tag "video2.jpg", alt: "photo"
        p class="opisanie" Описание
        p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui obcaecati facilis odit dolor tempora, magnam veritatis repellendus veniam numquam deserunt provident, 
          totam laborum perferendis quaerat nesciunt reprehenderit, officia fugiat maiores.
        p Impedit aspernatur dolorum temporibus ipsa eveniet molestiae illum nostrum earum aliquam, ea itaque consectetur porro accusamus praesentium ducimus veniam at soluta repudiandae, 
          et reprehenderit expedita. Cupiditate quaerat dolorem eligendi ipsam.

  div class="media"
    div class="one-media"
      span class="date" 13.07.2015
      a href="#" onclick="diplay_hide('#media-3');return false;" &nbsp;- Рекламный ролик №3
      div id="media-3" style="display: none;"
        div class="image"
          = image_tag "video1.jpg", alt: "photo"
        p class="opisanie" Описание
        p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque exercitationem, iure doloribus iste hic suscipit voluptates veniam odit debitis quidem consectetur optio non, 
          aspernatur neque culpa, provident laboriosam eligendi molestiae.
        p Quae eum provident voluptate architecto ipsa id exercitationem eos quia, saepe expedita doloremque, dolor, voluptates perferendis. Labore placeat praesentium facilis, 
          doloribus excepturi suscipit laborum, assumenda quae provident voluptatem, sed odit.
        p Tenetur consequuntur ea maxime minima maiores eveniet reprehenderit possimus atque numquam, explicabo voluptate error dolore labore aliquam ducimus vero amet nam, assumenda omnis, 
          laudantium animi unde! Quasi odit cumque eos.

app/views/static_pages/projects.html.slim
- provide :title, 'Проекты'

div class="page"
  div class="hs"
    table
      tr
        td style="width:20%" colspan="2" = image_tag "hs.png", style: "max-width:100%"
        td style="width:80%; text-align:left" colspan="5"
          p Мобильное приложение для работы с визитками и всей информацией по каждому контакту. Максимально автоматизированный функционал с использо
            ванием новейших технологий и полной защитой информации.
      tr
        td Микро и малый бизнес 
        td
        td Средний бизнес
        td
        td Крупный бизнес
        td
        td Частные пользователи
      tr
        td style="width:20%" = image_tag "house1.png", style: "max-width:100%"
        td style="width:6.66666%" = image_tag "arrow.png"
        td style="width:20%" = image_tag "house2.png", style: "max-width:100%"
        td style="width:6.66666%" = image_tag "arrow.png"
        td style="width:20%" = image_tag "house3.png", style: "max-width:100%"
        td style="width:6.66666%" = image_tag "arrow.png"
        td style="width:20%" = image_tag "house4.png", style: "max-width:100%"
      tr
        td colspan="3" style="color:#7CBDCF" 
          a href="" 
            | Презентация для компаний 
            i class="fa fa-angle-right"
        td colspan="4" style="color:#7CBDCF"
          a href="" 
            | Презентация для частных пользователей 
            i class="fa fa-angle-right"

    div class="video"
      iframe src="https://player.vimeo.com/video/130783833" width="100%" height="450" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen

    table class="hs_info"
      tr
        td style="background-color: #DEF2Fb"
          a href="projects1.html" Преимущества и цены
        td 
          a href="projects2.html" Загрузить
        td 
          a href="projects3.html" FAQ

    table class="hs_price"
      tr
        th Описание
        th Прайсинг
      tr
        td
          p style="text-align:justify" Универсальное мобильное приложение для работы с контактами. Максимально автоматизированный функционал с использование новейших технологий и 
            полной защитой информации
          p 
            i> class="fa fa-circle" 
            | Обмен визитками при касании телефонов
          p
            i> class="fa fa-circle"
            | Автоматическое заполнение доступной приложение информацией
          p 
            i> class="fa fa-circle"
            | Накопление истории взаимоотношений с каждым контактом
          p 
            i> class="fa fa-circle"
            | Шифрование информации на аппарате пользователя
          p
            i> class="fa fa-circle"
            | Электронно цифровая подпись
          p
            i> class="fa fa-circle"
            | Возможность интеграции приложения с любой CRM-системой компании
        td
          p style="padding-bottom:0em" 
            b Демо-версия
          p style="padding-top:0em; text-align:justify" После установки приложения на устройство в течение 1-го месяца бесплатное использование полного функционала, 
            с ограничением по накоплению полученных визиток не более 50шт.
          p style="padding-bottom:0em" 
            b Версия PRO (только для частных пользователей)
          p style="padding-top:0em; text-align:justify" Представляет функционал только по обмену и накоплению визитками без ограничений. Накопленная информация по встречами (календарь) 
            остается в приложении только для просмотра и не предполагает проведение активных операций пользователем.
          p style="padding-bottom:0em" Стоимость версии:
          p style="padding-top:0em" 15 долларов в год
          p style="padding-bottom:0em" 
            b Версия PRO+
          p style="padding-top:0em" Предлагает полный функционал приложения, представленный в демо-версии без ограничений
          p style="padding-bottom:0em" Стоимость версии для частного пользователя
          p style="padding-top:0em" 20 долларов в год
          p style="padding-bottom:0em" Стоимость версии для компании на одного пользователя
          p style="padding-top:0em" 100 долларов в год
        

app/views/users/new.html.slim
- provide :title, 'Регистрация GyreNation'

div id="signup" align="center"

  = form_for( @user ) do |f|

    div 
      = f.text_field :name, placeholder: "Ваше имя"

    div
      = f.text_field :email, placeholder: "Ваш email"

    div
      = f.password_field :password, placeholder: "Ваш пароль"

    div
      = f.password_field :password_confirmation, placeholder: "Подтвердите пароль:"

    div
      = f.submit "Зарегистрироваться"

app/views/users/show.html.slim
div#user_page align="center"

  h1 = @user.name
  h1 Это ваш личный кабинет